name: PR Deployment
'on':
  pull_request_target:
    types:
    - opened
    - synchronize
    - reopened
    branches:
    - main
concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true
env:
  LOCATION_NAME: westus
  PR_ENVIRONMENT_DIRECTORY: pr
permissions:
  id-token: write
  contents: read
  pull-requests: write
  checks: write
  actions: read
  security-events: write
  issues: read
jobs:
  Setup:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    outputs:
      locationName: ${{ steps.setValues.outputs.locationName }}
      prEnvironmentDirectory: ${{ steps.setValues.outputs.prEnvironmentDirectory }}
      environmentName: ${{ steps.setValues.outputs.environmentName }}
    steps:
    - name: Set Values
      id: setValues
      run: 'echo "locationName=$LOCATION_NAME" >> $GITHUB_OUTPUT

        echo "prEnvironmentDirectory=$PR_ENVIRONMENT_DIRECTORY" >> $GITHUB_OUTPUT


        suffix=$(uuidgen)


        # create a 6 character hash of the suffix

        suffixHash=$(echo -n "$suffix" | md5sum | cut -c1-6)


        echo "environmentName=$suffixHash" >> $GITHUB_OUTPUT

        '
  Validate:
    needs: Setup
    uses: ./.github/workflows/template.bicep.validate.yml
    with:
      environmentName: ${{ needs.Setup.outputs.environmentName }}
      environmentDirectory: ${{ needs.Setup.outputs.prEnvironmentDirectory }}
      locationName: ${{ needs.Setup.outputs.locationName }}
      branchName: ${{ github.head_ref }}
      githubEnvironment: symphony
    secrets: inherit
  NewEnvironment:
    needs:
    - Setup
    - Validate
    uses: ./.github/workflows/template.storeevent.yml
    with:
      pipelineName: PR
      eventName: NewEnvironment
      eventGroupId: PR-${{ github.event.pull_request.number }}-${{ github.repository_id
        }}
      data: Name=${{ needs.Setup.outputs.environmentName }} SHA=${{ github.event.pull_request.head.sha
        }} Location=${{ needs.Setup.outputs.locationName }} Name@odata.type=Edm.String
      githubEnvironment: symphony
      comment: "Creating environment with name: \"${{ needs.Setup.outputs.environmentName\
        \ }}\" using commit: \"${{ github.event.pull_request.head.sha }}\".\n\n${{\n\
        \  contains(github.event.pull_request.labels.*.name, 'preserve-pr-environment')\
        \ &&\n    format('The environment will not be destroyed after the workflow\
        \ completes.\\nTo delete it, use the [Destroy workflow](../actions/workflows/workflow.destroy.bicep.yml)\
        \ on the current branch with \"{0}\" as the environment name.', needs.Setup.outputs.environmentName)\n\
        \  ||\n    'The environment will be destroyed after the workflow completes.\\\
        nTo preserve it, add the \"preserve-pr-environment\" label to the PR.'\n}}\n"
    secrets: inherit
  PreviewDeployBaseBranch:
    needs:
    - Setup
    - NewEnvironment
    uses: ./.github/workflows/template.bicep.previewdeploy.yml
    with:
      environmentName: ${{ needs.Setup.outputs.environmentName }}
      environmentDirectory: ${{ needs.Setup.outputs.prEnvironmentDirectory }}
      locationName: ${{ needs.Setup.outputs.locationName }}
      branchName: ${{ github.base_ref }}
      githubEnvironment: symphony
    secrets: inherit
  PreviewDeployPRBranch:
    needs:
    - Setup
    - PreviewDeployBaseBranch
    uses: ./.github/workflows/template.bicep.previewdeploy.yml
    with:
      environmentName: ${{ needs.Setup.outputs.environmentName }}
      environmentDirectory: ${{ needs.Setup.outputs.prEnvironmentDirectory }}
      locationName: ${{ needs.Setup.outputs.locationName }}
      branchName: ${{ github.head_ref }}
      githubEnvironment: symphony
    secrets: inherit
  Test:
    needs:
    - Setup
    - PreviewDeployPRBranch
    uses: ./.github/workflows/template.bicep.test.yml
    with:
      environmentName: ${{ needs.Setup.outputs.environmentName }}
      locationName: ${{ needs.Setup.outputs.locationName }}
      branchName: ${{ github.head_ref }}
      githubEnvironment: symphony
    secrets: inherit
  Destroy:
    if: ${{ always() && !contains(github.event.pull_request.labels.*.name, 'preserve-pr-environment')
      }}
    needs:
    - Setup
    - Test
    uses: ./.github/workflows/template.bicep.destroy.yml
    with:
      environmentName: ${{ needs.Setup.outputs.environmentName }}
      locationName: ${{ needs.Setup.outputs.locationName }}
      branchName: ${{ github.head_ref }}
      githubEnvironment: symphony
    secrets: inherit
