name: PR Quality Checker
'on':
  pull_request:
    types:
    - opened
    - ready_for_review
    - synchronize
    - reopened
    branches:
    - main
concurrency:
  group: ${{ format('{0}-{1}-{2}', github.event_name, github.base_ref || github.ref,
    github.head_ref || github.event.number) }}
  cancel-in-progress: true
env:
  DEBUG: ${{ secrets.ACTIONS_RUNNER_DEBUG || vars.ACTIONS_RUNNER_DEBUG || secrets.ACTIONS_STEP_DEBUG
    || vars.ACTIONS_STEP_DEBUG || false }}
jobs:
  linter:
    name: MegaLinter
    runs-on: ubuntu-latest
    env:
      APPLY_FIXES: '- MARKDOWN_MARKDOWNLINT

        - MARKDOWN_MARKDOWN_TABLE_FORMATTER

        - SPELL_LYCHEE # When active, APPLY_FIXES must also be defined as environment
        variable (in github/workflows/mega-linter.yml or other CI tool)

        '
      APPLY_FIXES_EVENT: pull_request
      APPLY_FIXES_MODE: commit
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
    - name: "\U0001FA7A Debug"
      if: ${{ env.DEBUG == 'true' }}
      uses: raven-actions/debug@v1
      with:
        vars-context: ${{ toJson(vars) }}
        secrets-context: ${{ toJson(secrets) }}
        needs-context: ${{ toJson(needs) }}
        inputs-context: ${{ toJson(inputs) }}
    - name: "\u2935\uFE0F Checkout"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: "\U0001F9F9 MegaLinter"
      id: megalinter
      uses: oxsecurity/megalinter/flavors/documentation@v8
      env:
        GITHUB_TOKEN: ${{ github.token }}
        VALIDATE_ALL_CODEBASE: ${{ (contains(fromJSON('["push", "schedule", "workflow_dispatch"]'),
          github.event_name) && github.ref == 'refs/heads/main') || false }}
        REPOSITORY_GITLEAKS_PR_COMMITS_SCAN: ${{ (github.event_name == 'pull_request'
          && 'true') || 'false' }}
        JSON_JSONLINT_FILTER_REGEX_EXCLUDE: scripts/install/providers/azdo/templates
    - name: "\U0001F4E6 Archive MegaLinter artifacts"
      if: ${{ always() && (steps.megalinter.outcome == 'success' || steps.megalinter.outcome
        == 'failure') }}
      uses: actions/upload-artifact@v4
      with:
        name: MegaLinter reports
        path: 'megalinter-reports

          mega-linter.log

          '
    - name: "\U0001F916 Get bot details"
      if: ${{ steps.megalinter.outputs.has_updated_sources == 1 && (env.APPLY_FIXES_EVENT
        == 'all' || env.APPLY_FIXES_EVENT == github.event_name) && env.APPLY_FIXES_MODE
        == 'commit' && github.ref != 'refs/heads/main' && (github.event_name == 'push'
        || github.event.pull_request.head.repo.full_name == github.repository) }}
      id: bot-details
      uses: raven-actions/bot-details@v1
    - name: "\U0001F199 Commit and push applied linter fixes"
      if: ${{ steps.megalinter.outputs.has_updated_sources == 1 && (env.APPLY_FIXES_EVENT
        == 'all' || env.APPLY_FIXES_EVENT == github.event_name) && env.APPLY_FIXES_MODE
        == 'commit' && github.ref != 'refs/heads/main' && (github.event_name == 'push'
        || github.event.pull_request.head.repo.full_name == github.repository) }}
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref
          }}
        commit_message: 'style: apply linter fixes'
        commit_user_name: ${{ steps.bot-details.outputs.name }}
        commit_user_email: ${{ steps.bot-details.outputs.email }}
        commit_author: ${{ steps.bot-details.outputs.name-email }}
